### ISSUE TITLE
Update README file.

### ISSUE THREAD

**Issue by priyamaggarwal18** [Open-Source-Chandigarh/U-Move-Scan-to-Ride-Service#1]
So I want someone to Enhance the README file and make it attention grabbing for newcomers.

**Comment by fracergu** [comment]
Hi!, can I do this?

**Comment by priyamaggarwal18** [comment]
Hi @fracergu, what will you add in README ?

**Comment by fracergu** [comment]
@priyamaggarwal18 
Hi! since the project is at a very early stage, I think it would be interesting to add more detailed information on how to contribute. Having an initial design, it would also be interesting to add some image that catches the eye and you immediately perceive the type of product.

Adding some more information in the existing topics wouldn't be bad either.

I have something like this in mind:

![2023-10-20_10-45](https://github.com/Open-Source-Chandigarh/U-Move-Scan-to-Ride-Service/assets/17405480/5eec8edc-5ed1-4047-846c-2ebd9aad5eeb)

**Comment by priyamaggarwal18** [comment]
Great, go for it.

**Comment by pinak22dhir** [comment]
@priyamaggarwal18 you can code of conduct file
you can add code of conduct in readme.md
The code of conduct file should includes:
1.contribute to society and human well being
2. Be honest and Trustworthy
3. 3. Honor confidentiality
4. not knowingly use the surface that is obtained or retained illegally
5. improve their ability to create safe, reliable and quality software
6. respect the privacy of others
7. give proper credit for intellectual property
8. ensure adequate testing, debugging and review of software
